version: "3.8"

services:
  # Use `docker compose --profile retrieval-server up` to start the retrieval server
  retrieval-server:
    build:
      dockerfile: docker/Dockerfile.retrieval
      context: .
    image: vic/retrieval
    command: server
    volumes:
      - "./artifacts/:/app/artifacts/"
    ports:
      - "1234:1234"
