_target_: src.models.meruclip.CaSED_CLIP_MERU

defaults:
  - vocabulary: retrieval

model_name: "ViT-L-14"
alpha: 1.0 # no text component in eval

meru_config: "checkpoints/meru_clip_vit_L/train_clip_vit_l.py"
meru_ckpt: "checkpoints/meru_clip_vit_L/clip_vit_l.pth"
tau: 0.07 # from meru paper
use_softmax: False
use_meru_prompts: True
datasets_and_prompts: "src/utils/meru_utils/datasets_and_prompts.yaml"
# If the next two args are False, then it is a regular CaSED model
use_meru_for_classification: True
use_meru_for_augmentation: False