# @package _global_

defaults:
  - _self_
  - data: caltech101.yaml # choose data with `test_dataloader()` for evaluation
  - model: null
  - callbacks:
      - rich_progress_bar.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - experiment: baseline/clip.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is often necessary for evaluation
ckpt_path: null
